'use client'

import { useMemo, useState } from 'react'
import { Bell, BookOpen, Building2, ChevronDown, ChevronLeft, ClipboardList, GraduationCap, LayoutDashboard, Menu, MoreHorizontal, Plus, Search, ShieldCheck, SlidersHorizontal, Users, UserRound, ArrowLeftRight, CheckCircle2, Clock3, AlertTriangle, X, Languages } from 'lucide-react'

type Module = 'dashboard'|'students'|'guardians'|'academics'|'enrollment'|'transfers'
type Lang = 'ar'|'en'
type StudentRow = {id:string;name:string;en:string;grade:string;class:string;guardian:string;status:string;tone:string;updated:string}
const students: StudentRow[] = [
 {id:'ST-2024-1048',name:'سارة أحمد العتيبي',en:'Sara Ahmed Alotaibi',grade:'الصف الثالث متوسط',class:'3 / أ',guardian:'أحمد العتيبي',status:'نشط',tone:'success',updated:'اليوم، 09:42'},
 {id:'ST-2024-1047',name:'محمد خالد الحربي',en:'Mohammed Khaled Alharbi',grade:'الصف السادس ابتدائي',class:'6 / ب',guardian:'خالد الحربي',status:'نشط',tone:'success',updated:'اليوم، 09:18'},
 {id:'ST-2024-1039',name:'نورة فهد القحطاني',en:'Noura Fahad Alqahtani',grade:'الصف الأول ثانوي',class:'1 / أ',guardian:'فهد القحطاني',status:'معلّق',tone:'warning',updated:'أمس، 14:10'},
 {id:'ST-2024-1033',name:'عبدالله سالم الغامدي',en:'Abdullah Salem Alghamdi',grade:'الصف الثاني متوسط',class:'2 / ج',guardian:'سالم الغامدي',status:'نشط',tone:'success',updated:'أمس، 11:35'},
 {id:'ST-2024-1024',name:'ريم عبدالله الشهري',en:'Reem Abdullah Alshahri',grade:'الصف الرابع ابتدائي',class:'4 / أ',guardian:'عبدالله الشهري',status:'منقول',tone:'info',updated:'12 مايو، 10:05'},
]
const nav = [
 {id:'dashboard',label:'لوحة التحكم',en:'Dashboard',icon:LayoutDashboard}, {id:'students',label:'الطلاب',en:'Students',icon:GraduationCap}, {id:'guardians',label:'أولياء الأمور',en:'Guardians',icon:Users}, {id:'academics',label:'الهيكل الأكاديمي',en:'Academic structure',icon:Building2}, {id:'enrollment',label:'التسجيل والقبول',en:'Enrollment',icon:ClipboardList}, {id:'transfers',label:'التحويلات',en:'Transfers',icon:ArrowLeftRight},
]
const labels: Record<Module,{ar:string,en:string,crumb:string}> = {dashboard:{ar:'لوحة التحكم',en:'Dashboard',crumb:'الرئيسية'},students:{ar:'الطلاب',en:'Students',crumb:'شؤون الطلاب'},guardians:{ar:'أولياء الأمور',en:'Guardians',crumb:'شؤون الطلاب'},academics:{ar:'الهيكل الأكاديمي',en:'Academic Structure',crumb:'شؤون الطلاب'},enrollment:{ar:'التسجيل والقبول',en:'Enrollment',crumb:'شؤون الطلاب'},transfers:{ar:'التحويلات',en:'Transfers',crumb:'شؤون الطلاب'}}

export default function Home(){
 const [active,setActive]=useState<Module>('dashboard'); const [lang,setLang]=useState<Lang>('ar'); const [sidebar,setSidebar]=useState(true); const [query,setQuery]=useState(''); const [toast,setToast]=useState('');
 const rtl=lang==='ar'; const copy=(ar:string,en:string)=>rtl?ar:en; const title=labels[active];
 const filtered=useMemo(()=>students.filter(s=>(s.name+s.en+s.id).toLowerCase().includes(query.toLowerCase())),[query]);
 const notify=(msg:string)=>{setToast(msg);setTimeout(()=>setToast(''),2600)}
 return <div className={rtl?'min-h-screen':'min-h-screen ltr'} dir={rtl?'rtl':'ltr'}>
  <aside className={`fixed inset-y-0 ${rtl?'right-0':'left-0'} z-20 flex w-64 flex-col border-${rtl?'l':'r'} border-border bg-card transition-transform ${sidebar?'translate-x-0':'translate-x-full rtl:translate-x-full ltr:-translate-x-full'}`}>
   <div className="flex h-20 items-center gap-3 border-b border-border px-5"><div className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><ShieldCheck /></div><div><div className="font-bold text-primary">مدرستي</div><div className="text-xs text-muted-foreground">نظام إدارة المدرسة</div></div><button onClick={()=>setSidebar(false)} className="ms-auto text-muted-foreground lg:hidden" aria-label="close"><X /></button></div>
   <div className="flex items-center gap-3 border-b border-border px-5 py-5"><div className="flex size-10 items-center justify-center rounded-full bg-secondary font-bold text-primary">م</div><div className="min-w-0"><div className="truncate text-sm font-semibold">مدرسة النور الأهلية</div><div className="text-xs text-muted-foreground">الإدارة المدرسية</div></div></div>
   <nav className="flex flex-1 flex-col gap-1 p-3"><div className="px-3 pb-2 pt-3 text-[11px] font-semibold tracking-wide text-muted-foreground">{copy('شؤون الطلاب','STUDENT AFFAIRS')}</div>{nav.map(n=>{const I=n.icon;return <button key={n.id} onClick={()=>setActive(n.id as Module)} className={`flex items-center gap-3 rounded-lg px-3 py-3 text-sm transition ${active===n.id?'bg-primary text-primary-foreground shadow-sm':'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><I data-icon="inline-start" /> <span>{rtl?n.label:n.en}</span>{n.id==='transfers'&&<span className="ms-auto rounded-full bg-accent px-2 py-0.5 text-[10px] text-accent-foreground">4</span>}</button>})}</nav>
   <div className="m-3 rounded-lg bg-secondary p-3"><div className="mb-1 flex items-center gap-2 text-xs font-semibold text-primary"><BookOpen data-icon="inline-start" /> {copy('العام الدراسي','Academic year')}</div><div className="text-sm font-bold">1446 - 1447 هـ</div><div className="mt-1 text-xs text-muted-foreground">{copy('الفصل الدراسي الثاني','Second semester')}</div></div>
  </aside>
  <main className={`${sidebar?'lg:mr-64':'lg:mr-0'} min-h-screen transition-all`}>
   <header className="sticky top-0 z-10 flex h-20 items-center justify-between border-b border-border bg-card/95 px-4 backdrop-blur md:px-8"><div className="flex items-center gap-3"><button onClick={()=>setSidebar(!sidebar)} className="rounded-lg p-2 hover:bg-muted" aria-label="menu"><Menu /></button><div className="hidden items-center gap-2 text-sm text-muted-foreground sm:flex"><span>{title.crumb}</span><ChevronLeft className="size-4"/><span className="font-semibold text-foreground">{rtl?title.ar:title.en}</span></div></div><div className="flex items-center gap-2"><button onClick={()=>setLang(rtl?'en':'ar')} className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-muted-foreground hover:bg-muted"><Languages className="size-4"/><span>{rtl?'English':'العربية'}</span></button><button className="relative rounded-lg p-2 text-muted-foreground hover:bg-muted" aria-label="notifications"><Bell/><span className="absolute right-1 top-1 size-2 rounded-full bg-accent"/></button><div className="mx-1 hidden h-8 w-px bg-border sm:block"/><div className="flex items-center gap-2"><div className="flex size-9 items-center justify-center rounded-full bg-primary text-sm font-bold text-primary-foreground">م</div><div className="hidden text-sm sm:block"><div className="font-semibold">محمد العتيبي</div><div className="text-xs text-muted-foreground">مدير النظام</div></div><ChevronDown className="size-4 text-muted-foreground"/></div></div></header>
   <div className="mx-auto max-w-[1500px] p-4 md:p-8">{active==='dashboard'?<Dashboard setActive={setActive} copy={copy}/>:<ModuleView active={active} copy={copy} query={query} setQuery={setQuery} students={filtered} notify={notify}/>}</div>
  </main>
  {toast&&<div role="status" className="fixed bottom-5 left-1/2 z-30 flex -translate-x-1/2 items-center gap-2 rounded-lg bg-primary px-4 py-3 text-sm text-primary-foreground shadow-lg"><CheckCircle2 className="size-4"/>{toast}</div>}
 </div>
}

function Dashboard({setActive,copy}:{setActive:(m:Module)=>void,copy:(a:string,e:string)=>string}){return <div className="flex flex-col gap-7"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-sm font-medium text-accent"><span className="size-2 rounded-full bg-accent"/> {copy('الخميس، ٢٢ مايو ٢٠٢٥','Thursday, May 22, 2025')}</div><h1 className="text-3xl font-bold tracking-tight text-primary md:text-4xl">{copy('مرحباً، محمد','Welcome, Mohammed')}</h1><p className="mt-2 text-muted-foreground">{copy('إليك نظرة سريعة على العمليات الحالية في شؤون الطلاب.','Here is a quick look at current student affairs operations.')}</p></div><button onClick={()=>setActive('students')} className="flex w-fit items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground shadow-sm hover:opacity-90"><Plus className="size-4"/>{copy('إضافة طالب','Add student')}</button></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={GraduationCap} label={copy('إجمالي الطلاب','Total students')} value="1,248" foot={copy('مسجلون حالياً','Currently enrolled')} tone="blue"/><Stat icon={ClipboardList} label={copy('طلبات التسجيل','Enrollment requests')} value="18" foot={copy('تحتاج إلى مراجعة','Need review')} tone="teal"/><Stat icon={ArrowLeftRight} label={copy('طلبات التحويل','Transfer requests')} value="4" foot={copy('قيد الإجراء','In progress')} tone="amber"/><Stat icon={Users} label={copy('أولياء الأمور','Guardians')} value="1,106" foot={copy('ملفات مكتملة','Profiles complete')} tone="green"/></div>
 <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="font-bold text-primary">{copy('النشاط الأخير','Recent activity')}</h2><p className="mt-1 text-xs text-muted-foreground">{copy('آخر التحديثات على سجلات شؤون الطلاب','Latest student affairs record updates')}</p></div><button onClick={()=>setActive('students')} className="text-sm font-semibold text-accent">{copy('عرض الكل','View all')}</button></div><div className="flex flex-col">{[['سارة أحمد العتيبي','تحديث بيانات الطالب','اليوم، 09:42',UserRound],['طلب تسجيل جديد','عبدالرحمن صالح الدوسري','اليوم، 09:18',ClipboardList],['نورة فهد القحطاني','تم تعليق التسجيل للمراجعة','أمس، 14:10',AlertTriangle],['طلب تحويل TR-2025-004','بانتظار موافقة الإدارة','أمس، 11:35',ArrowLeftRight]].map(([a,b,c,I],i)=>{const Icon=I as typeof UserRound;return <div key={i} className="flex items-center gap-3 border-b border-border px-5 py-4 last:border-0"><div className="flex size-9 shrink-0 items-center justify-center rounded-full bg-secondary text-primary"><Icon className="size-4"/></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{a as string}</div><div className="truncate text-xs text-muted-foreground">{b as string}</div></div><span className="shrink-0 text-xs text-muted-foreground">{c as string}</span></div>})}</div></section><section className="card p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold text-primary">{copy('الوصول السريع','Quick access')}</h2><p className="mt-1 text-xs text-muted-foreground">{copy('ابدأ من أكثر المهام استخداماً','Start with common tasks')}</p></div><MoreHorizontal className="size-5 text-muted-foreground"/></div><div className="flex flex-col gap-2">{nav.slice(1).map(n=>{const I=n.icon;return <button key={n.id} onClick={()=>setActive(n.id as Module)} className="group flex items-center gap-3 rounded-lg border border-border p-3 text-start transition hover:border-accent hover:bg-secondary"><div className="flex size-9 items-center justify-center rounded-lg bg-muted text-primary group-hover:bg-card"><I className="size-4"/></div><span className="flex-1 text-sm font-semibold">{copy(n.label,n.en)}</span><ChevronLeft className="size-4 text-muted-foreground"/></button>})}</div></section></div>
 </div>}
function Stat({icon:Icon,label,value,foot,tone}:{icon:typeof GraduationCap,label:string,value:string,foot:string,tone:string}){return <div className="card flex items-start gap-4 p-5"><div className={`flex size-11 items-center justify-center rounded-xl ${tone==='teal'?'bg-secondary text-accent':tone==='amber'?'bg-[#fff4df] text-[#b87922]':tone==='green'?'bg-[#e5f5ee] text-[#1b8a67]':'bg-[#e8eff8] text-primary'}`}><Icon/></div><div><div className="text-sm text-muted-foreground">{label}</div><div className="mt-1 text-2xl font-bold text-primary">{value}</div><div className="mt-1 text-xs text-muted-foreground">{foot}</div></div></div>}

function ModuleView({active,copy,query,setQuery,students,notify}:{active:Module,copy:(a:string,e:string)=>string,query:string,setQuery:(s:string)=>void,students:StudentRow[],notify:(s:string)=>void}){const t=labels[active]; const isList=['students','guardians','enrollment','transfers'].includes(active); return <div className="flex flex-col gap-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 text-sm text-muted-foreground">{t.crumb} / {copy(t.ar,t.en)}</div><h1 className="text-3xl font-bold text-primary">{copy(t.ar,t.en)}</h1><p className="mt-2 text-muted-foreground">{copy(active==='students'?'إدارة السجلات الأساسية للطلاب ومتابعة حالتها.':active==='guardians'?'ملفات أولياء الأمور وروابطهم بالطلاب.':active==='academics'?'بنية العام الدراسي والمراحل والصفوف والفصول.':active==='enrollment'?'متابعة طلبات التسجيل والقبول وسجل الالتحاق.':'إدارة طلبات التحويل ومراجعة دورة حياة الطلب.','Manage records and operational workflows.')}</p></div><button onClick={()=>notify(copy('تم فتح نموذج الإضافة','Create form opened'))} className="flex w-fit items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><Plus className="size-4"/>{copy(active==='transfers'?'طلب تحويل جديد':'إضافة سجل جديد','Add new')}</button></div>{active==='academics'?<Academics copy={copy}/>:<><div className="grid gap-3 sm:grid-cols-3"><Mini label={copy('إجمالي السجلات','Total records')} value={active==='students'?'1,248':active==='guardians'?'1,106':active==='enrollment'?'18':'12'} /><Mini label={copy('نشط','Active')} value={active==='transfers'?'6':'1,192'} /><Mini label={copy('يحتاج إجراء','Needs action')} value={active==='transfers'?'4':'18'} alert /></div><section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-border p-4 md:flex-row md:items-center md:justify-between"><div className="relative max-w-md flex-1"><Search className="absolute right-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={copy('بحث بالاسم أو الرقم...','Search by name or ID...')} className="w-full rounded-lg border border-border bg-background py-2.5 pe-10 ps-3 text-sm outline-none focus:border-accent"/></div><div className="flex gap-2"><button className="flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm text-muted-foreground"><SlidersHorizontal className="size-4"/>{copy('تصفية','Filter')}</button><button onClick={()=>notify(copy('تم تجهيز التصدير','Export prepared'))} className="rounded-lg border border-border px-3 py-2 text-sm text-muted-foreground">{copy('تصدير','Export')}</button></div></div>{active==='students'?<StudentTable copy={copy} rows={students} notify={notify}/>:<GenericRows active={active} copy={copy} notify={notify}/>}</section></>}</div>}
function Mini({label,value,alert}:{label:string,value:string,alert?:boolean}){return <div className="card p-4"><div className="text-xs text-muted-foreground">{label}</div><div className={`mt-1 text-2xl font-bold ${alert?'text-[#b87922]':'text-primary'}`}>{value}</div></div>}
function StudentTable({copy,rows,notify}:{copy:(a:string,e:string)=>string,rows:StudentRow[],notify:(s:string)=>void}){return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-muted/60 text-xs text-muted-foreground"><tr>{['الطالب','الرقم التعريفي','الصف والفصل','ولي الأمر','الحالة','آخر تحديث',''].map((h,i)=><th key={i} className="px-5 py-3 text-start font-semibold">{copy(h,['Student','Student ID','Grade & class','Guardian','Status','Updated',''][i])}</th>)}</tr></thead><tbody>{rows.map(s=><tr key={s.id} className="border-t border-border hover:bg-muted/30"><td className="px-5 py-4"><div className="font-semibold text-primary">{copy(s.name,s.en)}</div></td><td className="px-5 py-4 font-mono text-xs text-muted-foreground">{s.id}</td><td className="px-5 py-4"><div>{s.grade}</div><div className="text-xs text-muted-foreground">{s.class}</div></td><td className="px-5 py-4 text-muted-foreground">{s.guardian}</td><td className="px-5 py-4"><span className={`badge ${s.tone}`}>{s.status}</span></td><td className="px-5 py-4 text-xs text-muted-foreground">{s.updated}</td><td className="px-5 py-4"><button onClick={()=>notify(copy(`تم فتح ملف ${s.name}`,`Opened ${s.en}`))} className="rounded-md p-2 text-muted-foreground hover:bg-muted"><MoreHorizontal className="size-4"/></button></td></tr>)}</tbody></table></div>}
function GenericRows({active,copy,notify}:{active:Module,copy:(a:string,e:string)=>string,notify:(s:string)=>void}){const rows=active==='guardians'?[['أحمد العتيبي','ولي أمر · 3 طلاب','3 طلاب مرتبطون','نشط'],['خالد الحربي','ولي أمر · طالب واحد','1 طالب مرتبط','نشط'],['فهد القحطاني','ولي أمر · طالب واحد','1 طالب مرتبط','يحتاج تحديث']]:active==='enrollment'?[['EN-2025-018','عبدالرحمن صالح الدوسري','الصف الرابع ابتدائي','قيد المراجعة'],['EN-2025-017','جود محمد السبيعي','الصف الأول متوسط','مقبول'],['EN-2025-016','ليان عبدالله الزهراني','الصف الثاني ثانوي','مستندات ناقصة']]:[['TR-2025-004','ريم عبدالله الشهري','داخلي · 4 / أ ← 5 / ب','قيد المراجعة'],['TR-2025-003','عمر ناصر المطيري','خارجي · إلى مدرسة الأمل','معتمد'],['TR-2025-002','هند صالح الغامدي','داخلي · 2 / أ ← 2 / ج','منفذ']];return <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-muted/60 text-xs text-muted-foreground"><tr>{(active==='guardians'?['ولي الأمر','الصفة','العلاقات','الحالة','']:active==='enrollment'?['رقم الطلب','الطالب','المرحلة والصف','الحالة','']:['رقم الطلب','الطالب','نوع التحويل والمسار','الحالة','']).map((h,i)=><th key={i} className="px-5 py-3 text-start font-semibold">{copy(h,['Name','Role','Relationships','Status',''][i])}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t border-border hover:bg-muted/30">{r.map((v,j)=><td key={j} className={`px-5 py-4 ${j===0?'font-mono text-xs text-muted-foreground':j===1?'font-semibold text-primary':'text-muted-foreground'}`}>{j===r.length-1?<span className={`badge ${v==='نشط'||v==='مقبول'||v==='منفذ'?'success':v==='معتمد'?'info':v==='قيد المراجعة'?'warning':'danger'}`}>{v}</span>:v}</td>)}<td className="px-5 py-4"><button onClick={()=>notify(copy('تم فتح التفاصيل','Details opened'))} className="rounded-md p-2 text-muted-foreground hover:bg-muted"><MoreHorizontal className="size-4"/></button></td></tr>)}</tbody></table></div>}
function Academics({copy}:{copy:(a:string,e:string)=>string}){return <div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><section className="card p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold text-primary">{copy('التسلسل الأكاديمي','Academic hierarchy')}</h2><button className="text-accent"><Plus className="size-4"/></button></div><div className="flex flex-col gap-2">{['العام الدراسي 1446 - 1447 هـ','المرحلة الابتدائية','المرحلة المتوسطة','المرحلة الثانوية'].map((x,i)=><div key={x} className={`flex items-center gap-3 rounded-lg p-3 ${i===2?'bg-secondary':'hover:bg-muted'}`}><ChevronLeft className="size-4 text-muted-foreground"/><span className="flex-1 text-sm font-semibold">{x}</span><span className="text-xs text-muted-foreground">{i===0?'الفصل الثاني':i===1?'6 صفوف':i===2?'3 صفوف':'3 صفوف'}</span></div>)}</div></section><section className="card overflow-hidden"><div className="border-b border-border p-5"><h2 className="font-bold text-primary">{copy('الفصول الدراسية','Classes')}</h2><p className="mt-1 text-xs text-muted-foreground">{copy('المرحلة المتوسطة / الصف الثالث متوسط','Middle school / Grade 9')}</p></div><div className="grid gap-3 p-5 sm:grid-cols-2">{[['3 / أ','28 / 30'],['3 / ب','26 / 30'],['3 / ج','30 / 30'],['3 / د','22 / 30']].map(([x,c],i)=><div key={x} className="rounded-lg border border-border p-4"><div className="flex justify-between"><span className="font-bold text-primary">{x}</span><span className="text-xs text-muted-foreground">{c}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full ${i===2?'bg-[#b87922]':'bg-accent'}`} style={{width:`${parseInt(c)*100/30}%`}}/></div><div className="mt-2 text-xs text-muted-foreground">{copy(i===2?'السعة مكتملة':'متاح للتسجيل','Capacity status')}</div></div>)}</div></section></div>}
